POST http://localhost:8888/products HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "description":"Daflon 500mg",
    "product_type_id":1
}
###

PUT http://localhost:8888/products/2 HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "description":"Teuto 100mg",
    "product_type":{
        "id": 1
    }
}
###

DELETE http://localhost:8888/products/2 HTTP/1.1
###

GET http://localhost:8888/products/2 HTTP/1.1
Content-Type: application/json
###

GET http://localhost:8888/products HTTP/1.1
Content-Type: application/json